### ISSUE TITLE
`atoms()` not defined

### ISSUE THREAD

**Issue by xamberl** [brainandforce/Electrum.jl#212]
I'm trying to print a .xyz file for a crystal. After using this snippet of code, `open(io -> writeXYZ(io, xcrystal), filename, write=true)`, I get this error.

```
ERROR: UndefVarError: atoms not defined
Stacktrace:
 [1] writeXYZ(io::IOStream, data::Crystal{3})
   @ Electrum ~/.julia/packages/Electrum/4WaPX/src/filetypes.jl:52
```

**Comment by brainandforce** [comment]
Fixed in the newest release version (0.1.18) which is being registered at the moment
